// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyProductAttribute("Expandable F# compiler")>]
[<assembly: AssemblyCopyrightAttribute("Author: Kouji Matsui, bleis-tift")>]
[<assembly: AssemblyCompanyAttribute("https://github.com/fscx-projects")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyProduct = "Expandable F# compiler"
    let [<Literal>] AssemblyCopyright = "Author: Kouji Matsui, bleis-tift"
    let [<Literal>] AssemblyCompany = "https://github.com/fscx-projects"
