// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Expandable F# compiler")]
[assembly: AssemblyVersionAttribute("0.9.2")]
[assembly: AssemblyFileVersionAttribute("0.9.2")]
[assembly: AssemblyCopyrightAttribute("Author: Kouji Matsui, bleis-tift")]
[assembly: AssemblyCompanyAttribute("https://github.com/fscx-projects")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "Expandable F# compiler";
        internal const System.String AssemblyVersion = "0.9.2";
        internal const System.String AssemblyFileVersion = "0.9.2";
        internal const System.String AssemblyCopyright = "Author: Kouji Matsui, bleis-tift";
        internal const System.String AssemblyCompany = "https://github.com/fscx-projects";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
