// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Expandable F# compiler")]
[assembly: AssemblyCopyrightAttribute("Kouji Matsui, bleis-tift")]
[assembly: AssemblyCompanyAttribute("https://github.com/fscx-projects")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "LocalBuild";
        internal const string InformationalVersion = "LocalBuild";
    }
}
