// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Expandable F# compiler")]
[assembly: AssemblyCopyrightAttribute("Author: Kouji Matsui, bleis-tift")]
[assembly: AssemblyCompanyAttribute("https://github.com/fscx-projects")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "Expandable F# compiler";
        internal const System.String AssemblyCopyright = "Author: Kouji Matsui, bleis-tift";
        internal const System.String AssemblyCompany = "https://github.com/fscx-projects";
    }
}
