// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyProductAttribute("Expandable F# compiler")>]
[<assembly: AssemblyVersionAttribute("0.9.1")>]
[<assembly: AssemblyFileVersionAttribute("0.9.1")>]
[<assembly: AssemblyCopyrightAttribute("Author: Kouji Matsui, bleis-tift")>]
[<assembly: AssemblyCompanyAttribute("https://github.com/fscx-projects")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyProduct = "Expandable F# compiler"
    let [<Literal>] AssemblyVersion = "0.9.1"
    let [<Literal>] AssemblyFileVersion = "0.9.1"
    let [<Literal>] AssemblyCopyright = "Author: Kouji Matsui, bleis-tift"
    let [<Literal>] AssemblyCompany = "https://github.com/fscx-projects"
    let [<Literal>] AssemblyConfiguration = "Release"
