// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FSharp.Expandable.Compiler")]
[assembly: AssemblyProductAttribute("fscx")]
[assembly: AssemblyDescriptionAttribute("Expandable F# compiler")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
        internal const string InformationalVersion = "0.0.1";
    }
}
